"""
Lightweight heuristic estimate of how "AI / vibe-coded" a submission looks.

Not a forensic detector — educational signal only.
"""

from __future__ import annotations

import ast
import re
from typing import Any


_GENERIC_MESSAGES = re.compile(
    r"^(update|fix|changes?|wip|asdf|test|commit|stuff|misc)\b",
    re.I,
)
_AI_COMMENT_MARKERS = re.compile(
    r"\b(generated by|chatgpt|gpt-4|copilot|claude|as an ai|here'?s a simple)\b",
    re.I,
)
_TEMPLATE_GREETING = re.compile(r"def\s+greet\s*\(|Hello,\s*\{?name", re.I)


def score_vibe_coded(
    files: dict[str, str],
    *,
    commit_message: str | None = None,
    diff: str | None = None,
) -> dict[str, Any]:
    """
    Return {score: 0-100, level, signals: [...], explanation}.
    Higher = more likely template / AI-styled code (heuristic).
    """
    py_files = {p: c for p, c in files.items() if p.endswith(".py")}
    if not py_files:
        return {
            "score": 0.0,
            "level": "n/a",
            "signals": [],
            "explanation": "No Python files to score for vibe-coding.",
        }

    signals: list[dict[str, Any]] = []
    points = 0.0

    total_lines = sum(c.count("\n") + 1 for c in py_files.values())
    docstring_lines = 0
    type_hint_funcs = 0
    total_funcs = 0
    magic_methods = 0
    comment_hits = 0
    greeting_hits = 0
    parse_ok = 0

    for path, content in py_files.items():
        if _TEMPLATE_GREETING.search(content):
            greeting_hits += 1
        if _AI_COMMENT_MARKERS.search(content):
            comment_hits += 1
            signals.append({"id": "ai_marker", "path": path, "detail": "AI-tool phrasing in comments/source"})

        try:
            tree = ast.parse(content)
            parse_ok += 1
        except SyntaxError:
            continue

        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                total_funcs += 1
                if node.name.startswith("__") and node.name.endswith("__"):
                    magic_methods += 1
                args = node.args
                annotated = bool(node.returns) or any(a.annotation for a in args.args)
                if annotated:
                    type_hint_funcs += 1
                doc = ast.get_docstring(node)
                if doc:
                    docstring_lines += doc.count("\n") + 1
            elif isinstance(node, ast.ClassDef):
                doc = ast.get_docstring(node)
                if doc:
                    docstring_lines += doc.count("\n") + 1

    # Dense perfect docs on tiny scripts often look generated
    if total_lines > 0 and docstring_lines / total_lines >= 0.25 and total_lines < 80:
        points += 18
        signals.append(
            {
                "id": "doc_density",
                "detail": f"High docstring density ({docstring_lines}/{total_lines} lines) on a short file",
            }
        )

    if total_funcs and type_hint_funcs / total_funcs >= 0.85 and total_funcs >= 1 and total_lines < 100:
        points += 14
        signals.append(
            {
                "id": "uniform_hints",
                "detail": f"Nearly all functions typed ({type_hint_funcs}/{total_funcs})",
            }
        )

    if greeting_hits:
        points += 22
        signals.append({"id": "template_greet", "detail": "Matches common starter greet() / Hello template"})

    if comment_hits:
        points += 25

    msg = (commit_message or "").strip()
    if not msg:
        points += 8
        signals.append({"id": "empty_message", "detail": "Empty commit message"})
    elif _GENERIC_MESSAGES.search(msg) or len(msg.split()) <= 2:
        points += 12
        signals.append({"id": "generic_message", "detail": f"Generic commit message: {msg!r}"})

    # Huge single-file dump with no tests
    if total_lines >= 120 and not any("test" in p.lower() for p in files):
        points += 10
        signals.append({"id": "large_untested", "detail": f"Large drop ({total_lines} lines) without tests"})

    # Tiny perfect-looking script
    if parse_ok == len(py_files) and 5 <= total_lines <= 25 and type_hint_funcs and docstring_lines:
        points += 10
        signals.append({"id": "tiny_polished", "detail": "Very short but fully polished starter style"})

    if diff:
        added = sum(1 for line in diff.splitlines() if line.startswith("+") and not line.startswith("+++"))
        if added >= 80:
            points += 8
            signals.append({"id": "large_diff", "detail": f"Large additive diff (+{added} lines)"})

    score = max(0.0, min(100.0, points))
    if score >= 70:
        level = "high"
    elif score >= 40:
        level = "medium"
    elif score >= 15:
        level = "low"
    else:
        level = "minimal"

    explanation = (
        f"Heuristic vibe-coded estimate: {score:.0f}% ({level}). "
        "This is a playful signal based on templates, polish patterns, and commit style — not proof of AI use."
    )
    return {
        "score": round(score, 1),
        "level": level,
        "signals": signals,
        "explanation": explanation,
    }
