"""
Lightweight heuristic estimate of how "AI / vibe-coded" a submission looks.

Not a forensic detector — educational signal only.
"""

from __future__ import annotations

import ast
import re
from typing import Any


_GENERIC_MESSAGES = re.compile(
    r"^(update|fix|changes?|wip|asdf|test|commit|stuff|misc|add|added|code)\b",
    re.I,
)
_AI_COMMENT_MARKERS = re.compile(
    r"\b("
    r"generated by|chatgpt|gpt-?4|gpt-?3|copilot|claude|gemini|as an ai|"
    r"here'?s a simple|hope this helps|let me know if|"
    r"certainly[!.,]|of course[!.,]|sure[,!]|"
    r"step\s*\d+|todo:\s*implement"  # sometimes left in scaffolds
    r")\b",
    re.I,
)
_TEMPLATE_GREETING = re.compile(r"def\s+greet\s*\(|Hello,\s*\{?name|Hello,\s*world", re.I)
_DOC_SECTIONS = re.compile(r"\b(Args|Arguments|Returns|Return|Raises|Yields|Example|Examples|Parameters|Notes)\s*:", re.I)
_RESTATE_COMMENTS = re.compile(
    r"^\s*#\s*(Initialize|Initialise|Create|Define|Return|Calculate|Iterate|Loop|Check|Ensure|Convert|Store|Get|Set)\b",
    re.M,
)
_FORMAL_PROSE = re.compile(
    r"\b(this (function|method|class|module)|ensures? that|in order to|provides? a|"
    r"responsible for|utiliz(?:e|es|ing)|leverages?|comprehensive)\b",
    re.I,
)
_TYPING_IMPORT = re.compile(
    r"^\s*(from typing import|from __future__ import annotations|from dataclasses import)",
    re.M,
)


def score_vibe_coded(
    files: dict[str, str],
    *,
    commit_message: str | None = None,
    diff: str | None = None,
) -> dict[str, Any]:
    """
    Return {score: 0-100, level, signals: [...], explanation}.
    Higher = more likely template / AI-styled code (heuristic).
    """
    py_files = {p: c for p, c in files.items() if p.endswith(".py")}
    if not py_files:
        return {
            "score": 0.0,
            "level": "n/a",
            "signals": [],
            "explanation": "No Python files to score for vibe-coding.",
        }

    signals: list[dict[str, Any]] = []
    points = 0.0

    total_lines = sum(max(1, c.count("\n") + (0 if c.endswith("\n") else 1)) for c in py_files.values())
    docstring_lines = 0
    docstring_funcs = 0
    type_hint_funcs = 0
    total_funcs = 0
    total_classes = 0
    comment_lines = 0
    parse_ok = 0
    long_names = 0
    identifier_count = 0

    combined = "\n".join(py_files.values())

    if _TEMPLATE_GREETING.search(combined):
        points += 20
        signals.append({"id": "template_greet", "detail": "Matches common starter greet() / Hello template"})

    if _AI_COMMENT_MARKERS.search(combined):
        points += 22
        signals.append({"id": "ai_marker", "detail": "AI-tool or chat-style phrasing in comments/source"})

    if _DOC_SECTIONS.search(combined):
        points += 14
        signals.append({"id": "doc_sections", "detail": "Structured docstring sections (Args/Returns/Example)"})

    restate_hits = len(_RESTATE_COMMENTS.findall(combined))
    if restate_hits >= 2:
        points += 12
        signals.append(
            {"id": "restate_comments", "detail": f"Step-by-step comments that restate code ({restate_hits})"}
        )
    elif restate_hits == 1:
        points += 6
        signals.append({"id": "restate_comments", "detail": "Comment restates an obvious code step"})

    if _FORMAL_PROSE.search(combined):
        points += 10
        signals.append({"id": "formal_prose", "detail": "Formal tutorial-style prose in docs/comments"})

    typing_hits = len(_TYPING_IMPORT.findall(combined))
    if typing_hits:
        points += min(12, 6 * typing_hits)
        signals.append({"id": "typing_imports", "detail": "Heavy typing/dataclass/future-annotations imports"})

    if re.search(r"class\s+Solution\b", combined):
        points += 16
        signals.append({"id": "leetcode_solution", "detail": "LeetCode-style class Solution pattern"})

    for path, content in py_files.items():
        comment_lines += sum(1 for line in content.splitlines() if line.lstrip().startswith("#"))
        try:
            tree = ast.parse(content)
            parse_ok += 1
        except SyntaxError:
            continue

        for node in ast.walk(tree):
            if isinstance(node, ast.Name):
                identifier_count += 1
                if len(node.id) >= 18:
                    long_names += 1
            if isinstance(node, ast.ClassDef):
                total_classes += 1
                doc = ast.get_docstring(node)
                if doc:
                    docstring_lines += doc.count("\n") + 1
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                total_funcs += 1
                args = node.args
                annotated = bool(node.returns) or any(a.annotation for a in args.args)
                if annotated:
                    type_hint_funcs += 1
                doc = ast.get_docstring(node)
                if doc:
                    docstring_funcs += 1
                    docstring_lines += doc.count("\n") + 1

    # Continuous polish signals (not all-or-nothing)
    if total_funcs:
        hint_ratio = type_hint_funcs / total_funcs
        doc_ratio = docstring_funcs / total_funcs
        if hint_ratio >= 0.5:
            pts = round(8 + 12 * hint_ratio)
            points += pts
            signals.append(
                {
                    "id": "type_hints",
                    "detail": f"High type-hint coverage ({type_hint_funcs}/{total_funcs})",
                }
            )
        if doc_ratio >= 0.5:
            pts = round(8 + 12 * doc_ratio)
            points += pts
            signals.append(
                {
                    "id": "docstrings",
                    "detail": f"High docstring coverage ({docstring_funcs}/{total_funcs})",
                }
            )

    if total_lines > 0 and docstring_lines / total_lines >= 0.15:
        points += 10
        signals.append(
            {
                "id": "doc_density",
                "detail": f"High docstring density ({docstring_lines}/{total_lines} lines)",
            }
        )

    if total_lines > 0 and comment_lines / total_lines >= 0.12 and comment_lines >= 2:
        points += 8
        signals.append(
            {
                "id": "comment_density",
                "detail": f"Dense narrating comments ({comment_lines}/{total_lines} lines)",
            }
        )

    if identifier_count and long_names / max(1, identifier_count) >= 0.08 and long_names >= 2:
        points += 8
        signals.append(
            {
                "id": "long_identifiers",
                "detail": f"Many long descriptive identifiers ({long_names})",
            }
        )

    # Overly complete module for a small task
    if total_classes and total_funcs >= 3 and total_lines < 120:
        points += 8
        signals.append({"id": "mini_framework", "detail": "Small file structured like a mini framework"})

    if re.search(r'if\s+__name__\s*==\s*[\'"]__main__[\'"]', combined) and total_lines < 80:
        points += 6
        signals.append({"id": "demo_main", "detail": "Includes polished __main__ demo block"})

    msg = (commit_message or "").strip()
    if not msg:
        points += 8
        signals.append({"id": "empty_message", "detail": "Empty commit message"})
    elif _GENERIC_MESSAGES.search(msg) or len(msg.split()) <= 3:
        points += 10
        signals.append({"id": "generic_message", "detail": f"Generic commit message: {msg!r}"})

    if total_lines >= 80 and not any("test" in p.lower() for p in files):
        points += 8
        signals.append({"id": "large_untested", "detail": f"Large drop ({total_lines} lines) without tests"})

    if parse_ok == len(py_files) and 8 <= total_lines <= 40 and (type_hint_funcs or docstring_funcs):
        points += 8
        signals.append({"id": "tiny_polished", "detail": "Short but polished starter-style script"})

    if diff:
        added = sum(1 for line in diff.splitlines() if line.startswith("+") and not line.startswith("+++"))
        if added >= 40:
            points += 6
            signals.append({"id": "large_diff", "detail": f"Large additive diff (+{added} lines)"})

    # Soft floor: perfectly parseable, no tests, mid-size clean file still looks a bit vibe
    if parse_ok == len(py_files) and total_funcs >= 1 and points < 15 and 15 <= total_lines <= 200:
        if not any("test" in p.lower() for p in files) and (type_hint_funcs or docstring_funcs or typing_hits):
            points += 12
            signals.append(
                {
                    "id": "clean_untouched",
                    "detail": "Clean typed/documented code with no rough edges (common LLM look)",
                }
            )

    score = max(0.0, min(100.0, points))
    # Mild curve so mid signals don't look like "nothing"
    if 0 < score < 100:
        score = round(min(100.0, score * 1.05), 1)

    if score >= 70:
        level = "high"
    elif score >= 40:
        level = "medium"
    elif score >= 20:
        level = "low"
    else:
        level = "minimal"

    explanation = (
        f"Heuristic vibe-coded estimate: {score:.0f}% ({level}). "
        "Playful signal from templates, polish, docs, and commit style — not proof of AI use."
    )
    return {
        "score": round(score, 1),
        "level": level,
        "signals": signals,
        "explanation": explanation,
    }
